# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : https://lyandyjoe.github.io/


title : lyandyjoe



author:
  name: 娇爷
  role: Android高级工程师一枚
  email: lyandyjoe@gmail.com
  github: lyandyjoe
  twitter: lyandyjoe
  facebook: lyandyjoe
  googleplus: +lyandyjoe
  bio: "我是李杨,一枚Android开发者,曾经就职于Accenture." 
  uno-dbyll: header_img.png
  #uno-dbyll: https://raw.githubusercontent.com/talk2ankan/uno-dbyll/gh-pages/uno-dbyll.png
